/**
 * k6 HTML Report - native (no external deps, CI-safe)
 * Output: k6-report/index.html
 */
export function handleSummary(data) {
  const m = data.metrics || {};
  const date = new Date().toISOString().slice(0, 10);

  const metricRow = (name, values) => {
    if (!values) return '';
    const v = values.values || {};
    return `<tr><td>${name}</td><td>${v.avg ?? '-'}</td><td>${v.min ?? '-'}</td><td>${v.med ?? '-'}</td><td>${v.max ?? '-'}</td><td>${v['p(90)'] ?? '-'}</td><td>${v['p(95)'] ?? '-'}</td></tr>`;
  };

  const metricsHtml = Object.entries(m)
    .filter(([, v]) => v && typeof v === 'object')
    .map(([name, v]) => metricRow(name, v))
    .join('');

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Task Manager Load Test ${date}</title>
  <style>
    body { font-family: system-ui,sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; }
    h1 { color: #333; }
    table { border-collapse: collapse; width: 100%; margin-top: 1rem; }
    th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
    th { background: #f5f5f5; }
    .pass { color: green; } .fail { color: red; }
  </style>
</head>
<body>
  <h1>Task Manager Load Test – ${date}</h1>
  <p>Generated by k6</p>
  <h2>Metrics</h2>
  <table>
    <thead><tr><th>Metric</th><th>Avg</th><th>Min</th><th>Med</th><th>Max</th><th>p(90)</th><th>p(95)</th></tr></thead>
    <tbody>${metricsHtml}</tbody>
  </table>
</body>
</html>`;

  return { 'k6-report/index.html': html };
}
